name: 'torrdav'
version: '3'
services:
  torrdav:
    build:
      context: .
      dockerfile: Dockerfile
    image: vjdev1212/torrdav:latest
    container_name: torrdav
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - TORRSERVER_URL=http://192.168.1.10:5665
      - HOST=0.0.0.0
    restart: always
